FROM python:3.6.14-alpine3.14
RUN  pip3 install requests Flask  ipip-ipdb  html2text
ADD  ./app  /app
WORKDIR /app
EXPOSE 5000/tcp

CMD ["python3", "-m", "app"]

# github源码：https://github.com/hongwenjun/ip

# docker镜像：https://hub.docker.com/r/hongwenjun/ip
